version: '3.8'
services:
  consul:
    image: consul:1.15
    ports:
      - "8500:8500"
    command: "agent -dev -client=0.0.0.0"

  bookservice:
    image: your-docker-registry/bookservice:latest
    depends_on:
      - consul
    environment:
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500
      - SERVICE_NAME=book-service
    deploy:
      replicas: 3
    ports:
      - "8080-8082:8080-8082" # map 3 ports (host->container) when testing locally (adjust as needed)
    restart: always
    # Nếu bạn muốn mỗi container có ID riêng, đặt SERVICE_INSTANCE_INDEX qua docker run/compose ext
